version: '3'

services:
  mysql:
    container_name: drupal_isp_admin_ui_mysql
    image: "mysql:5.7"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: drupal__
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
  drupal:
    container_name: drupal_isp_admin_ui_drupal
    depends_on:
      - "mysql"
    environment:
      - DRUSH_OPTIONS_URI=http://127.0.0.1
      - SIMPLETEST_BASE_URL=http://127.0.0.1
      - SYMFONY_DEPRECATIONS_HELPER=disabled
    build:
      context: .
      dockerfile: ./.docker/drupal/Dockerfile
    ports:
      - 80:80
    volumes:
      - ~/.composer/cache:/root/.composer/cache
      - ./.docker:/root/.docker
      - ./demo:/var/www/drupal:rw

volumes:
  db_data:
